Use gtest via autotools
https://github.com/bibledit/cloud/issues/910

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -657,6 +657,8 @@ COMPILERCLANG_FALSE
 COMPILERCLANG_TRUE
 COMPILERGCC_FALSE
 COMPILERGCC_TRUE
+GTEST_LIBS
+GTEST_CFLAGS
 PUGIXML_LIBS
 PUGIXML_CFLAGS
 GUMBO_LIBS
@@ -820,7 +822,9 @@ UTF8PROC_LIBS
 GUMBO_CFLAGS
 GUMBO_LIBS
 PUGIXML_CFLAGS
-PUGIXML_LIBS'
+PUGIXML_LIBS
+GTEST_CFLAGS
+GTEST_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1496,6 +1500,9 @@ Some influential environment variables:
               C compiler flags for PUGIXML, overriding pkg-config
   PUGIXML_LIBS
               linker flags for PUGIXML, overriding pkg-config
+  GTEST_CFLAGS
+              C compiler flags for GTEST, overriding pkg-config
+  GTEST_LIBS  linker flags for GTEST, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -5280,9 +5287,14 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
     if test x$ac_success = xno; then
-                for alternative in ${ax_cxx_compile_alternatives}; do
-      for switch in -std=c++${alternative} +std=c++${alternative} "-h std=c++${alternative}"; do
-        cachevar=`printf "%s\n" "ax_cv_cxx_compile_cxx17_$switch" | $as_tr_sh`
+                    for alternative in ${ax_cxx_compile_alternatives}; do
+      for switch in -std=c++${alternative} +std=c++${alternative} "-h std=c++${alternative}" MSVC; do
+        if test x"$switch" = xMSVC; then
+                                        switch=-std:c++${alternative}
+          cachevar=`printf "%s\n" "ax_cv_cxx_compile_cxx17_${switch}_MSVC" | $as_tr_sh`
+        else
+          cachevar=`printf "%s\n" "ax_cv_cxx_compile_cxx17_$switch" | $as_tr_sh`
+        fi
         { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether $CXX supports C++17 features with $switch" >&5
 printf %s "checking whether $CXX supports C++17 features with $switch... " >&6; }
 if eval test \${$cachevar+y}
@@ -7459,6 +7471,85 @@ else
 printf "%s\n" "yes" >&6; }
 
 printf "%s\n" "#define HAVE_PUGIXML 1" >>confdefs.h
+
+fi
+
+
+
+# Check whether the GTest library is available.
+
+pkg_failed=no
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for gtest >= 1.10.0" >&5
+printf %s "checking for gtest >= 1.10.0... " >&6; }
+
+if test -n "$GTEST_CFLAGS"; then
+    pkg_cv_GTEST_CFLAGS="$GTEST_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtest >= 1.10.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtest >= 1.10.0") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTEST_CFLAGS=`$PKG_CONFIG --cflags "gtest >= 1.10.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GTEST_LIBS"; then
+    pkg_cv_GTEST_LIBS="$GTEST_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtest >= 1.10.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtest >= 1.10.0") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTEST_LIBS=`$PKG_CONFIG --libs "gtest >= 1.10.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GTEST_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "gtest >= 1.10.0" 2>&1`
+        else
+	        GTEST_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "gtest >= 1.10.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GTEST_PKG_ERRORS" >&5
+
+	{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: Install gtest to also build the unit tests." >&5
+printf "%s\n" "$as_me: Install gtest to also build the unit tests." >&6;}
+elif test $pkg_failed = untried; then
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+	{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: Install gtest to also build the unit tests." >&5
+printf "%s\n" "$as_me: Install gtest to also build the unit tests." >&6;}
+else
+	GTEST_CFLAGS=$pkg_cv_GTEST_CFLAGS
+	GTEST_LIBS=$pkg_cv_GTEST_LIBS
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+
+printf "%s\n" "#define HAVE_GTEST 1" >>confdefs.h
 
 fi
 
